import { Tool, ToolCategory } from './types';

export const APP_NAME = "TurboConverter";

export const TOOLS: Tool[] = [
  // --- POPULAR ---
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one unified document.',
    category: ToolCategory.POPULAR,
    iconName: 'Files',
    acceptedFormats: '.pdf',
    allowMultiple: true,
    supportsBatch: false,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds.',
    category: ToolCategory.POPULAR,
    iconName: 'Image',
    acceptedFormats: 'image/*',
    allowMultiple: true,
    supportsBatch: false,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG or extract all images.',
    category: ToolCategory.POPULAR,
    iconName: 'Image',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'pdf-reader',
    name: 'PDF Reader',
    description: 'View PDFs directly in the browser without external software.',
    category: ToolCategory.POPULAR,
    iconName: 'BookOpen',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },

  // --- OPTIMIZE PDF ---
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'Scissors',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Select and remove specific pages from your PDF.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'Trash2',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate specific pages of a PDF by 90°, 180° or 270°.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'RotateCw',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size by optimizing content and stripping metadata.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'FileDown',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'watermark-pdf',
    name: 'Add Watermark',
    description: 'Add a text watermark diagonally across all pages of a PDF.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'Stamp',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'organize-pdf',
    name: 'Reorder Pages',
    description: 'Rearrange pages in a PDF by specifying a new page sequence.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'ArrowUpDown',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Add sequential page numbers to an existing PDF.',
    category: ToolCategory.PDF_OPTIMIZE,
    iconName: 'Hash',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: true,
  },

  // --- CONVERT TO PDF ---
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert an HTML file into a downloadable PDF document.',
    category: ToolCategory.PDF_CONVERT_TO,
    iconName: 'Globe',
    acceptedFormats: '.html,.htm',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description: 'Convert PNG images to PDF documents.',
    category: ToolCategory.PDF_CONVERT_TO,
    iconName: 'Image',
    acceptedFormats: 'image/png',
    allowMultiple: true,
    supportsBatch: false,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents (.docx) to PDF.',
    category: ToolCategory.PDF_CONVERT_TO,
    iconName: 'FileText',
    acceptedFormats: '.doc,.docx',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets (.xlsx) to PDF.',
    category: ToolCategory.PDF_CONVERT_TO,
    iconName: 'Table',
    acceptedFormats: '.xls,.xlsx',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations (.pptx) to PDF.',
    category: ToolCategory.PDF_CONVERT_TO,
    iconName: 'Presentation',
    acceptedFormats: '.ppt,.pptx',
    allowMultiple: false,
    supportsBatch: false,
  },

  // --- CONVERT FROM PDF ---
  {
    id: 'pdf-to-word',
    name: 'PDF to Text',
    description: 'Extract text content from a PDF into a .txt file.',
    category: ToolCategory.PDF_CONVERT_FROM,
    iconName: 'FileText',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Convert each PDF page into a high-quality PNG image.',
    category: ToolCategory.PDF_CONVERT_FROM,
    iconName: 'Image',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },

  // --- PDF SECURITY ---
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove PDF password security.',
    category: ToolCategory.PDF_SECURITY,
    iconName: 'Unlock',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF with a password.',
    category: ToolCategory.PDF_SECURITY,
    iconName: 'Shield',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Draw or upload a signature and place it on a specific page.',
    category: ToolCategory.PDF_SECURITY,
    iconName: 'PenTool',
    acceptedFormats: '.pdf',
    allowMultiple: false,
    supportsBatch: false,
  },

  // --- IMAGE TOOLS ---
  {
    id: 'compress-img',
    name: 'Compress Image',
    description: 'Compress JPG, PNG, SVG or GIF with best quality.',
    category: ToolCategory.IMAGE,
    iconName: 'Minimize',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'resize-img',
    name: 'Resize Image',
    description: 'Define your image dimensions.',
    category: ToolCategory.IMAGE,
    iconName: 'Maximize',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'convert-img',
    name: 'Convert Image',
    description: 'Convert between JPG, PNG, WEBP.',
    category: ToolCategory.IMAGE,
    iconName: 'RefreshCw',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'crop-img',
    name: 'Crop Image',
    description: 'Crop your image to a specific area or aspect ratio.',
    category: ToolCategory.IMAGE,
    iconName: 'Crop',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: false,
  },
  {
    id: 'grayscale-img',
    name: 'Grayscale Image',
    description: 'Convert a color image to black and white.',
    category: ToolCategory.IMAGE,
    iconName: 'Contrast',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'flip-img',
    name: 'Flip Image',
    description: 'Flip your image horizontally or vertically.',
    category: ToolCategory.IMAGE,
    iconName: 'FlipHorizontal',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: true,
  },
  {
    id: 'rotate-img',
    name: 'Rotate Image',
    description: 'Rotate your image by 90°, 180° or 270°.',
    category: ToolCategory.IMAGE,
    iconName: 'RotateCw',
    acceptedFormats: 'image/*',
    allowMultiple: false,
    supportsBatch: true,
  },
];
